//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using UnityEngine;
using UnityEngine.UI;
using System.Collections.Generic;

namespace GeneratedUiBindings
{
    public class TestBinding : MonoBehaviour
    {
        public Text ScreenHeaderTxt;
        public Image CreditsImg;
        public Text CreditsTxt;
        public Image DiamondsImg;
        public Text DiamondsTxt;
        public Text ChestTitleTxt;
        public List<Text> ChestCountTxt;
        public List<Text> ChestPriceTxt;
        public Text DiamondsTitleTxt;
        public List<Text> PlatinumCountTxt;
        public List<Text> PlatinumPriceTxt;
        public Text CreditsTitleTxt;
        public List<Text> CreditsCountTxt;
        public List<Text> CreditsPriceTxt;
    }
}

