//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using UnityEngine;
using UnityEngine.UI;
using System.Collections.Generic;
using CycladeBase.Utils;
using CycladeBindings.UIStateSystem;
using CycladeBindings.UIStateSystem.Base;

namespace GeneratedCycladeBindings
{
    public class CardBinding : MonoBehaviour
    {
        public enum CurrencyType
        {
            Credits,
            Diamonds,
            Real,
        }

        public enum ProductType
        {
            Credits1,
            Credits2,
            Credits3,
            Credits4,
            Diamond1,
            Diamond2,
            Diamond3,
            Diamond4,
            Diamond5,
            Diamond6,
            Chest,
            ChestBig,
        }

        public enum CardType
        {
            Simple,
            CardWithAdditionalInfo,
        }

        public Button BackBlockBtn;
        public Image IconImg;
        public TMPro.TextMeshProUGUI CountTxt;
        public TMPro.TextMeshProUGUI AdditionalTextTxt;
        public Image CurrencyIconImg;
        public TMPro.TextMeshProUGUI PriceTxt;
 
        public List<BaseStatefulElement> statefulElements;

        private CurrencyType _currencyType = default;
        private ProductType _productType = default;
        private CardType _cardType = default;

        public void SetState(CurrencyType currencyType, ProductType productType, CardType cardType)
        {
            _currencyType = currencyType;
            _productType = productType;
            _cardType = cardType;
            UpdateElements();
        }

        public void SetState(CurrencyType currencyType)
        {
            _currencyType = currencyType;
            UpdateElements();
        }

        public void SetState(ProductType productType)
        {
            _productType = productType;
            UpdateElements();
        }

        public void SetState(CardType cardType)
        {
            _cardType = cardType;
            UpdateElements();
        }

        private void UpdateElements()
        {
            UIStateSystemHelper.SetState(new Enum[]
            {
                _currencyType, 
                _productType, 
                _cardType
            }, statefulElements);
        }
    }
}

