//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using UnityEngine;
using UnityEngine.UI;
using System.Collections.Generic;

namespace GeneratedCycladeBindings
{
    public class ExampleShopBinding : MonoBehaviour
    {
        public CycladeUI.Test.Components.ExampleComponent Top;
        public Text ScreenHeaderTxt;
        public Image CreditsImg;
        public Text CreditsTxt;
        public Image DiamondsImg;
        public Text DiamondsTxt;
        public Image QuestionImg;
        public Text ChestTitleTxt;
        public List<Image> ChestIconImgList;
        public List<Text> ChestCountTxtList;
        public List<Text> ChestPriceTxtList;
        public Text DiamondsTitleTxt;
        public List<Image> DiamondIconImgList;
        public List<Text> DiamondCountTxtList;
        public List<Text> DiamondPriceTxtList;
        public Text CreditsTitleTxt;
        public List<Image> CreditsIconImgList;
        public List<Text> CreditsCountTxtList;
        public List<Text> CreditsPriceTxtList;
    }
}

