//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using UnityEngine;
using UnityEngine.UI;
using System.Collections.Generic;
using CycladeBase.Utils;
using CycladeBindings.UIStateSystem;
using CycladeBindings.UIStateSystem.Base;

namespace GeneratedCycladeBindings
{
    public class ShopPopupBinding : MonoBehaviour
    {
        public UnityEngine.RectTransform Bg;
        public CycladeUIExample.Components.ExampleComponentForBind Top;
        public Text ScreenHeaderTxt;
        public GameObject SeparatorGo;
        public Image DiamondsImg;
        public Text DiamondsTxt;
        public Image CreditsImg;
        public Text CreditsTxt;
        public Image QuestionImg;
        public GameObject ContentGo;
        public TMPro.TextMeshProUGUI ChestsTitleTxt;
        public ViewInstances<GeneratedCycladeBindings.CardBinding> ChestCardBindInstances;
        public TMPro.TextMeshProUGUI DiamondsTitleTxt;
        public ViewInstances<GeneratedCycladeBindings.CardBinding> DiamondCardBindInstances;
        public TMPro.TextMeshProUGUI CreditsTitleTxt;
        public ViewInstances<GeneratedCycladeBindings.CardBinding> CreditsCardBindInstances;
    }
}

